### ISSUE TITLE
Homepage redesign for phase 2

### ISSUE THREAD

**Issue by cmiller02** [risd/risd-congratulations-v2-ph2#2]
@rubillionaire I'm opening this issue for the build of the phase 2 homepage redesign. @mmarol 's wireframe for the homepage will, hopefully, get finalized next week - when I will be away. Therefore, I've asked @mmarol to please add his finalized wireframe and specs to this issue so that you can begin work on this (as your top priority) as soon as his design work is done.

Just to make sure that I'm putting this request in the right repository - the homepage redesign would go here: https://welcome-ph2.risd.systems/, which will eventually point to welcome.risd.edu when Regular Decision students are notified of their acceptance in mid March.

Anyway, thanks so much to you both!

**Comment by mmarol** [comment]
@rubillionaire here's the approved mockups for the changes
https://www.figma.com/proto/SgbtHoMWsdS34rVD3SoyZ8/Phase-2?node-id=63%3A1372&viewport=1333%2C224%2C0.18317288160324097&scaling=min-zoom

Let me know if you need anything else!

**Comment by mmarol** [comment]
@rubillionaire we'd also want the CMS content type for the homepage to change to have more discreet fields for each section of the page. For example, Hero, Dates, Sections, Videos. Maybe @cmiller02 could help define what those are? Also @cmiller02 was going to think about the phasing question you had and get back to you about it.

**Comment by mmarol** [comment]
Oh one extra note, the section of the homepage that leads to the various sections of the site has one exception, which is the admitted students day, which leads to a specific page. Not sure how you want to deal with that in the CMS but that box will always be a featured page I think.

**Comment by rubillionaire** [comment]
i published some changes to the site. there are now section index pages as seen here: https://welcome-ph2.risd.systems/next-steps/

these pages are now linked to from the footer navigation as well as the side bar navigation.

the side bar navigation has been updated to more closely match the mock ups. the biggest difference is the direction that the sections are ordered in. the mockup goes top to bottom, left to right. where as the site goes left to right, top to bottom. this is necessary given that we are scrolling vertically, and we are filling a horizontal space, so we need to list our items horizontally and let them stack up vertically. if we were to scroll horizontally, we could switch to match the mock up, but that would break consistency with the rest of the site.

i'll work on the home page next.

@mmarol let me know how things are looking!

**Comment by rubillionaire** [comment]
there is now a first cut of the home page up. @cmiller02 put some content in to get us started, and there is enough to see how each of the modules will look.

let me know what y'all think!

just a reminder that i will be traveling next Tuesday to the following Wednesday (3rd-11th). i'll have my computer with me but i know a few of those days i won't be able to do much with my computer, so it would be nice to get as much done before then as possible. i'll be around through the week to update things in response to any feedback.

**Comment by mmarol** [comment]
@rubillionaire it's feeling pretty good! There's a few things on first glance:

- Could we bump the statement text and the text in the image and video boxes to all be 44px (with 48px leading for the statement)
- Could the statement text be max-width: 30em
- the alternating color blocks should be white and the yellow that's applied to the BRDD strip
- Could we set the images to either always crop to 1200x600 or at least stretch to fill the space and I can provide images that are 2:1 or whatever ratio we decide?
- interested in the nav width just being 3 columns wide instead of filling like 95% of the screen. Will run it by Jordan.
- The section landing pages look good!

**Comment by rubillionaire** [comment]
@mmarol killer! thanks for the feedback.

- statement and text and video boxes are all at 44px / 48px. this wasn't part of the type scale, so i made a homepage specific variable to house these sizes

- good call on the max width! i never run into these issues on my tiny screen.

- images are now cropped to 1200x600. we can always switch it up. once we land on something i can update the content type directions to specify the dimensions.

- not sure what you mean by the nav comment. do you mean always having it be 3 columns and having a horizontal scroll? for context, the original nav is 16rem wide. the next breakpoint (medium) bumps it up to 32rem, then the final breakpoint (large) bumps it up another 16rem to 48rem. so we get 3 columns out of it at the wider breakpoints without taking up more screen than necessary.

- glad to hear the section landing pages look good! im happy that those were introduced, feels a bit more complete with them in place.

**Comment by mmarol** [comment]
@rubillionaire with the nav, I just meant having the container be 95% window width (let's just say 100% window width for ease) regardless of window size. and then the nav item columns stack like you have them right now.

**Comment by rubillionaire** [comment]
@mmarol ahhh okay i see. let me know if you want that to be the case. it already is on mobile, i can see the parity working on larger screens.

**Comment by mmarol** [comment]
@rubillionaire taking a deeper look now and here are more changes:
- can the Welcome to RISD SVG have padding to the left and right of it on smaller screens?
<img width="987" alt="Screen Shot 2020-02-28 at 16 03 09" src="https://user-images.githubusercontent.com/6997772/75587703-12085280-5a45-11ea-9597-2a9dbd640f0b.png">

- can the font-sizes for the h2 text be brought down to 36px? I thought it was fine in the figma file but it's feeling clunky
<img width="1513" alt="Screen Shot 2020-02-28 at 16 12 30" src="https://user-images.githubusercontent.com/6997772/75587821-5ac00b80-5a45-11ea-8c8a-4f5d2bda20b0.png">

- can the video box title be the same font-size at the questions strip?
<img width="1513" alt="Screen Shot 2020-02-28 at 16 13 54" src="https://user-images.githubusercontent.com/6997772/75587832-5e539280-5a45-11ea-8d41-b576dfc4f82d.png">

- can the titles of the videos have the same hover state as the links to the pages?

- can the active state for the nav items be an underline instead of a color change? it's odd because the section titles are the same color as the active state right now

- can all the type sizes come down to 24px on mobile
<img width="433" alt="Screen Shot 2020-02-28 at 16 22 00" src="https://user-images.githubusercontent.com/6997772/75588371-8263a380-5a46-11ea-97d0-a7d3cbe945ef.png">

- can all the footer type sizes come down to 16px on mobile?
<img width="447" alt="Screen Shot 2020-02-28 at 16 23 07" src="https://user-images.githubusercontent.com/6997772/75588566-f3a35680-5a46-11ea-932b-aada2acd7933.png">

I'll take another pass on Monday morning to make sure I didn't miss anything.

**Comment by mmarol** [comment]
@rubillionaire few more things:
- the border-bottom on the active nav items feels weird, can we do `text-decoration: underline;` instead? and can this happen on the section headers as well when you're on a section landing page?
<img width="895" alt="Screen Shot 2020-03-02 at 14 59 24" src="https://user-images.githubusercontent.com/6997772/75712844-a0bfde00-5c96-11ea-8cb1-815997623579.png">

- can we add a `padding-top: 0.5rem;` to the `.home-module__image-link-text` elements?
<img width="1665" alt="Screen Shot 2020-03-02 at 15 03 18" src="https://user-images.githubusercontent.com/6997772/75713032-03b17500-5c97-11ea-9020-abf2196788cc.png">

- Can the "A look inside" text be uppercase on mobile? don't think this is the best solution but it'll do for now.
<img width="418" alt="Screen Shot 2020-03-02 at 15 06 38" src="https://user-images.githubusercontent.com/6997772/75713265-84707100-5c97-11ea-95a9-a16065a59aed.png">

- Space above "NEXT STEPS" is very large for some reason. Can it match the space at the bottom of the box?
<img width="415" alt="Screen Shot 2020-03-02 at 15 07 50" src="https://user-images.githubusercontent.com/6997772/75713353-a964e400-5c97-11ea-9df8-b7cf936112b3.png">

- not sure why the mobile nav is not getting wider but instead forcing this line break?
<img width="412" alt="Screen Shot 2020-03-02 at 15 09 59" src="https://user-images.githubusercontent.com/6997772/75713541-006ab900-5c98-11ea-821c-406c4d1d59a9.png">

- can we have a separate image field in the CMS for the mobile hero images on the section landing pages? the super short banners work on desktop but mobile would use taller images.
<img width="415" alt="Screen Shot 2020-03-02 at 15 11 35" src="https://user-images.githubusercontent.com/6997772/75713727-61928c80-5c98-11ea-803c-05ed2a191a78.png">

- there's some extra space above the "reserve your space" int the footer that could be removed.
<img width="316" alt="Screen Shot 2020-03-02 at 15 15 09" src="https://user-images.githubusercontent.com/6997772/75713991-dd8cd480-5c98-11ea-886f-23836410bcf7.png">

I think that should be it.

**Comment by rubillionaire** [comment]
@mmarol i have updated the site to reflect the changes you outlined.

i also updated the [README][readme-ph2] for the repo to include a section on how to contribute. below that are notes on deployment configuration. between the two you should have what you need to make further changes.

i will go ahead and outline the steps that will be required to have this site publish to welcome.risd.edu, in case you want to make the switch while i am unavailable. i will do my best to be available thurs-tues.

### to publish this repo to welcome.risd.edu

1. Go through steps 1-3 of the [README][readme-ph1] in order to be able to manipulate phase 1 version of the site's deploy configuration.
2. From within the repo for `risd-congratulations-v2` (phase 1), run the command `npx rm-wh deploys:remove welcome.risd.edu --branch=master` to disconnect welcome.risd.edu from the master branch of the phase 1 repo.
3. From within the phase 2 repo, ensure git flow is set up, `git flow init`. if it is not set up, use all of the defaults to get it started.
4. Create a new release by running `git flow release start v1.0.0`. This will create a new branch, `release/v1.0.0`.
5. Finish the release by running `git flow release finish v1.0.0`, this will merge the branch into the master branch.
6. Checkout the master branch by running `git checkout master`
7. Set the deploy configuration to map this branch to welcome.risd.edu by running `npx rm-wh deploys:set welcome.risd.edu --branch=master`
8. Deploy the site with the new deployment configuration `npm run deploy`. Once deployed the next build of the site will publish to welcome.risd.edu using the templates from the phase 2 repository.
9. Ensure to push changes from the develop branch to github by running `git checkout develop` to switch branches, and `git push` to push the changes to github.

[readme-ph2]:https://github.com/risd/risd-congratulations-v2-ph2/blob/develop/README.md#to-contribute
[readme-ph1]:https://github.com/risd/risd-congratulations-v2/blob/develop/README.md#to-contribute

**Comment by cmiller02** [comment]
@mmarol - I believe that @rubillionaire addressed all concerns particular to this issue. Any reason I can't close this up?
