### ISSUE TITLE
Modals once per session

### ISSUE THREAD

**Issue by mmarol** [risd/risd-congratulations-v2-ph2#4]
@rubillionaire can we have the homepage modal only show up once per session? Going back to the homepage to see it pop up again is a little frustrating.

**Comment by cmiller02** [comment]
Thanks for this as well - @mmarol ! I went in to create this issue and found that you already had.

**Comment by rubillionaire** [comment]
@cmiller @mmarol i have updated the modal to only show on first visit to the home page per browser. the modal will also not show up if you open a new tab and navigate directly to there, or if you are on another page of the site and navigate to the home page; both of these scenarios lean on the same browser information.

**Comment by cmiller02** [comment]
@rubillionaire - I think that right now we're not seeing the modal come up at all. When I came in this morning I didn't see it on Chrome after refreshing-where I had left the site open from yesterday-so I then went to Firefox and Safari, where I hadn't been viewing it yesterday, but didn't see the modal in either case either. If we could base things on a thirty minute internet session that would be great-just so that we have some middle ground of someone not constantly seeing it if they hop back and forth to the homepage, but that they would, say, if they went idle for a while and then went back to the site a bit later.

**Comment by rubillionaire** [comment]
@cmiller02 i have updated the home page modal to operate based on the 30 minute session that you suggested instead of the single dismissal. the session starts when the modal is dismissed. so you will see it once again if its the first time visiting the site since transitioning to this new way of operating, and the sessions will be tracked between page loads.

let me know how its working for you!

**Comment by cmiller02** [comment]
I think that all is working really well @rubillionaire - I checked and I see the modal when I first launch the homepage, but if I refresh the homepage or switch to another page and then come back I don't see it. However, when I refreshed the homepage 40+ min after my initial launch I saw it again! Yay! @mmarol do you have any concerns at all? Thanks so much for the work @rubillionaire !
