### ISSUE TITLE
Open RISD Page changes

### ISSUE THREAD

**Issue by mmarol** [risd/risd-congratulations-v2-ph2#6]
@rubillionaire there are a few changes to this page that will require CMS changes.

- The hero image moment would need an option to be an embeddly widget to hold a livestream video. Treating the video like commencement livestream video in terms of size etc would be ideal https://commencement2018.risd.edu/.
- We will want to be able to switch the current page (https://welcome-ph2.risd.systems/open-risd/) to the sketches below at some point after the livestream happens and have this page become an archive of the videos. If this switch requires us to just delete some content from the CMS and add the videos that sounds good.
- I don't think there's a module for this in the CMS, but we would want a list of vimeo videos as illustrated below.
- I think the Supporting Content content type should be able to handle the text block at the bottom of the sketch?

![Section Landing Desktop-1](https://user-images.githubusercontent.com/6997772/76646798-fc5d5780-6531-11ea-93cd-2e3019e8e442.png)
![Section Landing Desktop](https://user-images.githubusercontent.com/6997772/76646799-fc5d5780-6531-11ea-8768-b38a9e717365.png)

**Comment by mmarol** [comment]
I will temporarily update the Open RISD page to house a gif without cropping it like it currently does. Stop-gap before the video module is implemented.
```
.page__hero--desktop {
    height: 100%;
    background-size: contain;
    background-position: center;
    background-repeat: no-repeat;
    background-color: black;
}
```

**Comment by rubillionaire** [comment]
@mmarol some updates, let me know how things are lookin to you!

- there is a new Hero Video field in the CMS. its been styled the same as the hero video on the [2018 commencement site][2018-commencement]

- it looks like your mockup doesn't use the centered page name just below the hero. so any item with a hero video will not display the page name at the top of the page. Instead it is assumed that there is a list of videos, whose section is started with the contents of the `Univerisal - Video Title` field, which is aligned left.

- the list of videos is powered by the `Universal - Video` relationshop in the `Universal - Pages` content type. i wasn't sure if the OPEN RISD text and the arrow over the video were for me to execute on, but let me know. i could see adding an overlay that could be dismissed with a click. if the underlying player has an API, we could start the video on that same click potentially.

- the link list at the bottom of the page is powered by the `Universal - Link` content type. there is a relationship to it from the `Universal - Pages` content type. These links are styled in the same fashion as the link list of every `Section` page.

- check out the [test page][test-page] and the corresponding [test content type entry][test-content-type]

[2018-commencement]:https://commencement2018.risd.edu/
[test-page]:http://welcome-ph2.risd.systems/_wh_previews/universalpages/4516d0cb-fcb2-47a3-f44f-66189ec254e9/
[test-content-type]:https://welcome-ph2.risd.systems/cms/#/wh/content/universalpages/-M3IQH-HUitDBKCCfKWE

**Comment by mmarol** [comment]
@rubillionaire just few updates and questions based on our meeting:

Here's mockups of where the videos would show up. I think we can just use the existing modules for both the homepage and the other pages?
https://www.figma.com/proto/SgbtHoMWsdS34rVD3SoyZ8/Phase-2?node-id=1684%3A59&viewport=720%2C767%2C0.2410714328289032&scaling=min-zoom

Could we add a description field to the Video content type so it would show up as shown in the ^ mockups? It would not show up on the homepage, but would on the universal pages.

We should be able to do everything else in the mockups with what you've already set up right?

**Comment by rubillionaire** [comment]
the "Info Session Archive" videos will need another set of fields in the CMS to accommodate them. that should be easy to do though, we can re-purpose the template and styles associated with the first set of videos under "A Look Inside".

Adding a description field to the `Universal Video` content type. we can conditionally render them if they are there, so they can be part of any `Universal - Pages` instance that has a relationship to them.

i can update the type styles on the `Univerisal - Video Title` field of `Universal - Pages` to match your mockup, looks like mine is currently set in a larger spec.

when are you trying to get this launched? just wondering how to prioritize with the homepage work thats being done.

**Comment by cmiller02** [comment]
hey @rubillionaire - edu homepage work should take priority - as I knew that has a hard deadline of Thursday, April 9 for launch. Do you think you could give me a sense of how long the above work that you outlined would take you to get done? (Just for planning purposes so that I can set expectations with Admissions.)

**Comment by rubillionaire** [comment]
@mmarol i've pushed some changes

- the homepage now has a second set of video fields, under the title `Video 2 Fields`. this can be used to create the "Info Session Archive" section in your homepage mockup.

- there is now a `Video Description` field in the `Universal - Video` content type. it renders text below a video when its listed on a `Universal - Page`

- the type styles for the `Video Title` and `Video 2 Title` have been updated to be h3's instead of h2's, and they are centered like other section titles.

check out the [test page][test-page] and its [content type entry][test-content-type] to see how its set up. feel free to adjust the content to verify that it can handle what you need. i played with it a bit and it was looking right. and the homepage is set up to handle the quote + video set up you mocked up. thats live at the [staging homepage][staging-homepage]

let me know how it all looks. only thing to do before deploying is to disable the quote + video on the homepage since they are just filled with placeholder content that sounds like it won't be set until friday. and the video lists can be used anytime after we deploy.

[test-page]:http://welcome-ph2.risd.systems/_wh_previews/universalpages/4516d0cb-fcb2-47a3-f44f-66189ec254e9/
[test-content-type]:https://welcome-ph2.risd.systems/cms/#/wh/content/universalpages/-M3IQH-HUitDBKCCfKWE
[staging-homepage]:http://welcome-ph2.risd.systems

**Comment by mmarol** [comment]
@rubillionaire could we set the max-width on the description to 30em? That's the only change I can see after testing it out.
<img width="1792" alt="Screen Shot 2020-04-09 at 11 03 04" src="https://user-images.githubusercontent.com/6997772/78909585-bf618380-7a51-11ea-9bf2-cbe97b1c52c1.png">

**Comment by rubillionaire** [comment]
@mmarol totally! thanks for the feedback.

i just pushed this to the staging site. i'll see about coordinating a deployment

**Comment by rubillionaire** [comment]
the changes that came from this issue have been deployed! im going to close it up for now.
